### ISSUE TITLE
where is source code?

### ISSUE THREAD

**Issue by newpost** [MonkSoul/Fur#1]

**Comment by MonkSoul** [comment]
https://gitee.com/monksoul/Fur

**Comment by yang-er** [comment]
Can you set up a automatic pipeline to sync Gitee source with GitHub? You can close issue/PR here.

**Comment by MonkSoul** [comment]
ok，i will sync tomorrow

**Comment by MonkSoul** [comment]
https://github.com/MonkSoul/Fur
