### ISSUE TITLE
我看了上次freesql作者黑你的帖子，想聊聊

### ISSUE THREAD

**Issue by tonyqus** [MonkSoul/Fur#4]
你好，由于最近那个什么ncc组织老在隔壁群黑我，昨天我朋友给我喂了好几个ncc的瓜，我其实当时有些懵逼+震惊的状态，真的服现在的国内.net社区。

他们给我喂的瓜里面也有freesql, sqlsugar的瓜，以及你的Fur，然后我就去看了某帖子，但说句实话哦，某人骂你的帖子里面说了半天，都没聊技术的事，我就纳闷现在比技术都可以用嘴的吗？各种人身攻击，而不是用数据做性能比较的吗？比如benchmarkdotnet出个报告，你看我的库性能比你好这么多。

有兴趣的话咱们私聊下

**Comment by MonkSoul** [comment]
> 你好，由于最近那个什么ncc组织老在隔壁群黑我，昨天我朋友给我喂了好几个ncc的瓜，我其实当时有些懵逼+震惊的状态，真的服现在的国内.net社区。
> 
> 他们给我喂的瓜里面也有freesql, sqlsugar的瓜，以及你的Fur，然后我就去看了某帖子，但说句实话哦，某人骂你的帖子里面说了半天，都没聊技术的事，我就纳闷现在比技术都可以用嘴的吗？各种人身攻击，而不是用数据做性能比较的吗？比如benchmarkdotnet出个报告，你看我的库性能比你好这么多。
> 
> 有兴趣的话咱们私聊下

好的，是非天天有，不听自然无。💪我的QQ号：8020292，微信号：ibaiqian

**Comment by 312855935** [comment]
我们需要像你这样专注于底层研究的人，不要在乎一些键盘侠的攻击，努力做好自己就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MonkSoul/Fur"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月15日(星期四) 上午7:07
收件人:&nbsp;"MonkSoul/Fur"<Fur@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [MonkSoul/Fur] 我看了上次freesql作者黑你的帖子，想聊聊 (#4)





  
你好，由于最近那个什么ncc组织老在隔壁群黑我，昨天我朋友给我喂了好几个ncc的瓜，我其实当时有些懵逼+震惊的状态，真的服现在的国内.net社区。
 
他们给我喂的瓜里面也有freesql, sqlsugar的瓜，以及你的Fur，然后我就去看了某帖子，但说句实话哦，某人骂你的帖子里面说了半天，都没聊技术的事，我就纳闷现在比技术都可以用嘴的吗？各种人身攻击，而不是用数据做性能比较的吗？比如benchmarkdotnet出个报告，你看我的库性能比你好这么多。
 
有兴趣的话咱们私聊下
  
好的，是非天天有，不听自然无。�9�4我的QQ号：8020292，微信号：ibaiqian

**Comment by nodyang** [comment]
fur 加油

**Comment by MonkSoul** [comment]
> fur 加油

嗯嗯，一起加油。

**Comment by whtiehack** [comment]
fur 加油

**Comment by MonkSoul** [comment]
> fur 加油

嗯嗯，都要都要。
